version: '3.8'

services:
  react-app:
    image: my-react-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1  # Two instances for load balancing
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1  # Update one instance at a time
        delay: 5s  # Wait 5 seconds before updating the next instance
        order: start-first  # New container starts before the old one stops
    ports:
      - "8080:80"
    networks:
      - app-network
    volumes:
      - react-env-volume:/app/.env  # Mount .env file from volume

volumes:
  react-env-volume:
    external: true  # Use pre-created volume

networks:
  app-network:
    driver: overlay  # Changed to overlay for Swarm
